python main.py python-functions/nested_arr.py test
python main.py python-functions/case1.py case1
python main.py python-functions/case2.py case2
python main.py python-functions/case3.py case3
python main.py python-functions/case4.py case4
python main.py python-functions/case5.py case5
python main.py python-functions/case6.py case6
python main.py python-functions/char.py test
python main.py python-functions/intarr.py test
python main.py python-functions/allzero.py allzero
python main.py python-functions/comp.py comp
python main.py python-functions/list.py test
python main.py python-functions/triangle.py classify_triangle
